services:
  db:
    image: postgres:15-alpine
    container_name: postgres_encurtador_url
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '5968:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest_encurtador_url
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    command: >
      sh -c "
        sleep 5 &&
        yarn build &&
        yarn migrate:run &&
        yarn start:prod
      "

volumes:
  postgres_data:
